services:
  - type: web
    name: pa-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements_full.txt
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1 